apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-connect-backend
  labels:
    app: campus-connect-backend
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: "poll"
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/images: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: campus-connect-backend
  template:
    metadata:
      labels:
        app: campus-connect-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        - secretRef:
            name: {{ .Values.configMap.name }}-secrets
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=768"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # Backend needs to write logs
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: api/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: api/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3 