apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: campus-connect-backend
data:
  # Application Configuration
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  HOST: {{ .Values.config.host | quote }}
  PORT: "{{ .Values.config.port }}"
  API_PREFIX: {{ .Values.config.apiPrefix | quote }}
  SESSION_LIFETIME: {{ .Values.config.sessionLifetime | quote }}
  COOKIE_SECURE: {{ .Values.config.cookieSecure | quote }}
  COOKIE_SAME_SITE: {{ .Values.config.cookieSameSite | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
  DOMAIN: {{ .Values.domain | quote }}
  MONGO_HOST: {{ .Values.mongodb.host | quote }}
  MONGO_PORT: {{ .Values.mongodb.port | quote }}
  MONGO_DB: {{ .Values.mongodb.database | quote }}
  
  

