apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configMap.name }}-secrets
  labels:
    app: campus-connect-backend
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongodb_uri | b64enc }}
  REDIS_KEY: {{ .Values.secrets.redis_key | b64enc }}
  REDIS_PASSWORD: {{ .Values.secrets.redis_key | b64enc }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryption_key | b64enc }}
  SESSION_SECRET: {{ .Values.secrets.session_secret | b64enc }} 