# Shared Configuration for Campus Connect
domain: ""  # Set via --set in GitHub Actions

# Let's Encrypt Configuration
letsencrypt:
  email: ""  # Set via --set in GitHub Actions

# SSL Configuration
ssl:
  enabled: true
  issuer: "letsencrypt-prod"
  secretName: "campusconnect-tls"

# Ingress Configuration
ingress:
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"

# Network Policies
networkPolicies:
  enabled: true
  defaultDeny: true
