apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campus-connect-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.ssl.secretName }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: campus-connect-backend-service
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: campus-connect-frontend-service
            port:
              number: 80
