# # Default Deny All Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny-all
#   namespace: default
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   - Egress
# ---
# # Allow DNS resolution
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-dns
#   namespace: default
# spec:
#   podSelector: {}
#   policyTypes:
#   - Egress
#   egress:
#   - to: []
#     ports:
#     - protocol: UDP
#       port: 53
#     - protocol: TCP
#       port: 53
# ---
# # Allow kube-system communication
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-kube-system
#   namespace: default
# spec:
#   podSelector: {}
#   policyTypes:
#   - Egress
#   egress:
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
# ---
# # Backend Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: backend-network-policy
#   namespace: campus-connect
# spec:
#   podSelector:
#       app: campus-connect-backend
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: ingress-nginx
#     ports:
#     - protocol: TCP
#       port: 3000
#   - from:
#     - podSelector:
#         matchLabels:
#           app: campus-connect-frontend
#     ports:
#     - protocol: TCP
#       port: 3000
#   egress:
#   - to: []
#     ports:
#     - protocol: TCP
#       port: 53
#     - protocol: UDP
#       port: 53
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
#   - to:
#     - ipBlock:
#         cidr: 0.0.0.0/0
#     ports:

#     - protocol: TCP
#       port: 27017  # MongoDB port
# ---
# # Frontend Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: frontend-network-policy
#   namespace: campus-connect
# spec:
#   podSelector:
#     matchLabels:
#       app: campus-connect-frontend
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: ingress-nginx
#     ports:
#     - protocol: TCP
#       port: 80
#   egress:
#   - to: []
#     ports:
#     - protocol: TCP
#       port: 53
#     - protocol: UDP
#       port: 53
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
#   - to:
#     - podSelector:
#         matchLabels:
#           app: campus-connect-backend
#     ports:
#     - protocol: TCP
#       port: 3000
# ---
# # Ingress Controller Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: ingress-controller-policy
#   namespace: ingress-nginx
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: ingress-nginx
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - ipBlock:
#         cidr: 0.0.0.0/0
#     ports:
#     - protocol: TCP
#       port: 80
#     - protocol: TCP
#       port: 443
#   egress:
#   - to: []
#     ports:
#     - protocol: TCP
#       port: 53
#     - protocol: UDP
#       port: 53
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
#   - to:
#     - podSelector:
#         matchLabels:
#           app: campus-connect-backend
#     ports:
#     - protocol: TCP
#       port: 3000
#   - to:
#     - podSelector:
#         matchLabels:
#           app: campus-connect-frontend
#     ports:
#     - protocol: TCP
#       port: 80
# ---
# # Cert-Manager Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cert-manager-policy
#   namespace: cert-manager
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: cert-manager
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
#     ports:
#     - protocol: TCP
#       port: 9402
#   egress:
#   - to: []
#     ports:
#     - protocol: TCP
#       port: 53
#     - protocol: UDP
#       port: 53
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
#   - to:
#     - ipBlock:
#         cidr: 0.0.0.0/0
#     ports:
#     - protocol: TCP
#       port: 443  # Let's Encrypt ACME
#     - protocol: TCP
#       port: 80   # HTTP-01 challenge
# ---
# # Keel Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: keel-policy
#   namespace: keel
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: keel
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: ingress-nginx
#     ports:
#     - protocol: TCP
#       port: 9300
#   egress:
#   - to: []
#     ports:
#     - protocol: TCP
#       port: 53
#     - protocol: UDP
#       port: 53
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
