apiVersion: v1
kind: ResourceQuota
metadata:
  name: campus-connect-quota
  namespace: campus-connect
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
    services: "10"
    services.loadbalancers: "2"
    services.nodeports: "0"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: campus-connect-limits
  namespace: campus-connect
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod 