# Frontend Application Configuration
image:
  repository: ""  # Set via --set in GitHub Actions
  tag: ""         # Set via --set in GitHub Actions
  pullPolicy: Always

replicaCount: 1

service:
  name: campus-connect-frontend-service
  type: ClusterIP
  port: 80

# Application Configuration
config:
  nodeEnv: "production"
  port: 80
  apiUrl: "/api"
  domain: ""

# ConfigMap name
configMap:
  name: campus-connect-frontend-config

# Resource limits (optimized for B2s nodes)
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"


